#!/bin/bash

# Create a GKE cluster for staging
gcloud container clusters create "staging-cluster" \
    --zone "us-central1-a" \
    --num-nodes "3" \
    --machine-type "e2-standard-4"

# Create a GKE cluster for production
gcloud container clusters create "production-cluster" \
    --zone "us-central1-a" \
    --num-nodes "5" \
    --machine-type "e2-standard-4"
